apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T06:48:20Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2427"
  uid: c01acd20-ab72-45f6-b6c6-7bc807106033
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.181.91
  clusterIPs:
  - 10.106.181.91
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31207
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
